Macro_Cronograma_Core/Models/ErrorViewModel.cs
using System;

namespace Macro_Cronograma_Core.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Macro_Cronograma_Core/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Macro_Cronograma_Core.Models;
using Macro_Cronograma.services;
using Macro_Cronograma.models;

namespace Macro_Cronograma_Core.Controllers
{
    public class HomeController : Controller
    {
        macro_cronogramaContext db = new macro_cronogramaContext();

        public IActionResult Index()
        {
            return View(db.tb_projeto);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Macro_Cronograma_Core/Controllers/ProjetoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Macro_Cronograma.models;
using Macro_Cronograma.services;
using Macro_Cronograma_Core.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Macro_Cronograma_Core.Controllers
{
    public class ProjetoController : Controller
    {
        private macro_cronogramaContext db = new macro_cronogramaContext();
        private projeto projetoService = new projeto();
        private atividade atividadeService = new atividade();
        
        // GET: /<controller>/
        public IActionResult Projeto(int id)
        {
            ViewBag.ProjetoSelecionado 
                = projetoService.buscarProjeto(id);

            ViewBag.atividades =
                atividadeService.listarAtividadesProjeto(id);

            return View(db.tb_projeto);
        }

        public IActionResult Tables()
        {
            var projeto = db.tb_projeto.ToList();
            return View(projeto);
        }

        public JsonResult PopularGraficos(int idProjeto)
        {
            var populationList = atividadeService.listarAtividadesProjeto(idProjeto);
            return Json(populationList);
        }
    }
}

Macro_Cronograma_Core/Views/Home/Index.cshtml
<div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="page-header">Dashboard</h3>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <section>
            <!--area do grafico-->
        </section>


</div>
    

Macro_Cronograma_Core/Views/Projeto/Projeto.cshtml
@model IEnumerable<Macro_Cronograma.models.tb_projeto>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">@ViewBag.ProjetoSelecionado.des_projeto</h3>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Macro Cronograma
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="flot-chart">
                        <div class="flot-chart-content" id="flot-line-chart">
                            @Html.Partial("_atividades.cshtml")
                            @Html.Partial("_inserirAtividade.cshtml")
                            @Html.Partial("_inserirProjeto.cshtml")
                        </div>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>

    <!-- /#page-wrapper -->

Macro_Cronograma_Core/Views/Projeto/_atividades.cshtml
<section class="content-header">
    <h1>
        <span class="nome-projeto" id="project-title"></span>
    </h1>
</section>

<section class="content-body">

    <div class="row hidden-print" id="box-controles-atividades" style="margin-bottom: 20px;">

        <div class="col-lg-6" id="box-controles-atividades">
            <button type="button" class="btn btn-toolbar" id="btn-reduzir-escala">
                <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-toolbar" id="btn-aumentar-escala">
                <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
            <button type="button" class="btn btn-success" id="cadastrar-atividades" data-toggle="modal" data-target="#modalAtividades">
                Inserir atividade
            </button>
            <button type="button" class="btn btn-danger" id="excluir-atividades">
                Excluir atividade
            </button>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div id="timeline-tooltip"></div>
            <div id="alert-atividades"></div>
        </div>
    </div>

</section>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div id="chart_wrapper">
    <div id="chart_div"></div>
</div>
    <script type="text/javascript">

        google.charts.load('current', {
            packages: ['corechart', 'bar']
        });
        google.charts.setOnLoadCallback(LoadData);

        function LoadData() {
            var projeto = @ViewBag.ProjetoSelecionado.id_projeto;

            $.ajax({
                url: '@Url.Action("PopularGraficos","Projeto")',
                dataType: "json",
                data: { 'idProjeto': projeto},
                type: "GET",
                error: function(xhr, status, error) {
                    var err = eval("(" + xhr.responseText + ")");
                    toastr.error(err.message);
                },
                success: function(data) {
                    renderizar_grafico(data);
                    return false;
                }
            });
            return false;
        }

        function renderizar_grafico(atividades) {

            var colors = [];

            var format = 'dd/MM'

            google.charts.load('visualization', '1', { 'packages': ['timeline'] });
            google.charts.setOnLoadCallback(drawChart);
            function drawChart() {
                var container = document.getElementById('timeline-tooltip');
                var chart = new google.visualization.Timeline(container);
                var dataTable = new google.visualization.DataTable();
                var data_inicial;
                var data_final;


                dataTable.addColumn({ type: 'string', id: 'atividade' });
                dataTable.addColumn({ type: 'string', id: 'label' });
                dataTable.addColumn({ type: 'date', id: 'Start' });
                dataTable.addColumn({ type: 'date', id: 'End' });


                $.each(atividades, function (i, atividade) {

                    dataTable.addRow(
                        [
                            atividade.des_atividade,
                            convertDate(atividade.dt_inicio) + " a " + convertDate(atividade.dt_fim),
                            new Date(atividade.dt_inicio),
                            new Date(atividade.dt_fim)
                        ]
                    );
                    colors.push(atividade.cod_cor_grafico);

                    if (i == 0) {
                        data_inicial = new Date(atividade.dt_inicio);
                    }
                    data_final = new Date(atividade.dt_fim);

                })


                //if (zoom) {

                //    format = 'MM/yy'
                //    data_inicial = new Date
                //        (
                //            data_inicial.getFullYear(),
                //            data_inicial.getMonth() - 3,
                //            data_inicial.getDate()
                //        );

                //    data_final = new Date
                //        (
                //            data_final.getFullYear(),
                //            data_final.getMonth() + 3,
                //            data_final.getDate()
                //        );
                //}

                var options = {
                    colors: colors,
                    allowHtml: true,
                    showRowNumber: true,
                    height: 350,
                    timeline: {
                        rowLabelStyle: { fontName: 'verdana', fontSize: 9 },
                        barLabelStyle: { fontName: 'verdana', fontSize: 9, position: 'left' },
                    },

                    hAxis: {
                        format: format,
                        minValue: data_inicial,
                        maxValue: data_final,
                        gridlines: { count: 3 }
                    }


                };
                chart.draw(dataTable, options);
            }

            function convertDate(inputFormat) {
                function pad(s) { return (s < 10) ? '0' + s : s; }
                var d = new Date(inputFormat);
                return [pad(d.getDate()), pad(d.getMonth() + 1), d.getFullYear()].join('/');
            }



        }
    </script>

Macro_Cronograma_Core/Views/Projeto/_inserirAtividade.cshtml
@*@model IEnumerable<Macro_Cronograma.models.tb_atividade>*@

@*@Styles.Render("~/Content/ModalForms.css")*@

<div class="modal fade" id="modalAtividades" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="ModalLabel">Incluir nova atividade</h3>
                <div class="button-close-modal">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="fechar-modal-atividade">
                        <span aria-hidden="true"><i class="fa fa-close"></i></span>
                    </button>
                </div>
            </div>
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#incluiratividade"><b>Incluir Atividades:</b></a>
                        </h4>
                    </div>
                    <div id="incluiratividade" class="panel-collapse collapse in">
                        <div class="form-wrap col-sm-12">
                            @*@using (Ajax.BeginForm("cadastrarAtividade", "Home", new AjaxOptions
                            { HttpMethod = "POST", UpdateTargetId = "mx-3", OnSuccess = "OnSuccess", OnFailure = "OnFailure" }, new { @id = "form-atividades", UpdateTargetId = "sucess-atividade" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true)
                                @Html.HiddenFor(a => a.id_projeto)
                                <div class="form-group">
                                    @Html.ValidationMessageFor(a => a.des_atividade, null, new { @class = "error" })
                                    @Html.LabelFor(a => a.des_atividade)
                                    @Html.TextBoxFor(a => a.des_atividade, new { @id = "form34", @class = "form-control" })
                                </div>
                                <div class="checkbox">
                                    @Html.ValidationMessageFor(a => a.flag_deadline, null, new { @class = "error" })
                                    @Html.CheckBoxFor(a => a.flag_deadline, new { @class = "character-checkbox" })
                                    @Html.LabelFor(a => a.flag_deadline)
                                </div>
                                <div class="form-group" style="height:70px;">
                                    <div class="col-sm-6" style="padding-left:0;">
                                        @Html.LabelFor(a => a.dt_inicio)
                                        @Html.TextBoxFor(a => a.dt_inicio, new { @id = "input_des_projeto", @class = "form-control", @type = "date" })
                                        @Html.ValidationMessageFor(a => a.dt_inicio, null, new { @class = "error" })
                                    </div>
                                    <div class="col-sm-6 input-data" style="padding-right:0;">
                                        @Html.LabelFor(a => a.dt_fim)
                                        @Html.TextBoxFor(a => a.dt_fim, new { @id = "input_des_projeto", @class = "form-control", @type = "date" })
                                        @Html.ValidationMessageFor(a => a.dt_fim, null, new { @class = "error" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(a => a.cod_cor_grafico)
                                    @Html.DropDownListFor(a => a.cod_cor_grafico, new SelectList(ViewBag.DadosAtribuicao), new { @class = "form-control" })
                                </div>
                                <input type="submit" id="btn-submit" class="btn btn-custom btn-lg btn-block" value="Enviar">
                                <div id="result-atividade"></div>

                            }*@
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapse1"><b>Configurações de Atividades:</b></a>
                            </h4>
                        </div>
                        <div id="collapse1" class="panel-collapse collapse">
                            <div class="panel-body">
                                <ul style="list-style-type:none;">
                                    <li><input type="checkbox" /><b>Exemplo 1</b></li>
                                    <li><input type="checkbox" /><b>Exemplo 2</b></li>
                                    <li><input type="checkbox" /><b>Exemplo 3</b></li>
                                    <li><input type="checkbox" /><b>Exemplo 4</b></li>
                                    <li><input type="checkbox" /><b>Exemplo 5</b></li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    function OnSuccess(data) {
        document.getElementById('form-atividades').reset();
        document.getElementById('result-atividade').innerHTML = data.Mensagem;
    }
    function OnFailure(data) {
        console.log('HTTP Status Code: ' + data.param1 + '  Error Message: ' + data.param2);
    }

    $("#fechar-modal-atividade").click(function () {
        getAtividades($("#id_projeto").val());
    });
</script>

Macro_Cronograma_Core/Views/Projeto/_inserirProjeto.cshtml
@*@model IEnumerable<Macro_Cronograma.models.tb_projeto>*@

@{
    ViewBag.Title = "Incluir Novo Projetos";
}

@*@Styles.Render("~/Content/ModalForms.css")*@

<div class="modal fade" id="modalProjeto" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="ModalLabel">Incluir novo projeto</h3>
                <div class="button-close-modal">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"><i class="fa fa-close"></i></span>
                    </button>
                </div>
            </div>
            <div class="form-wrap">
                @*@using (Html.BeginForm("RegistrarProjeto", "Home", FormMethod.Post, new { @class = "form-signin" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        @Html.ValidationMessageFor(a => a.des_projeto, null, new { @class = "error" })
                        @Html.Label("Nome do projeto:")
                        @Html.TextBoxFor(a => a.des_projeto, new { @id = "input_des_projeto", @class = "form-control" })
                    </div>
                    <input type="submit" class="btn btn-custom btn-lg btn-block" value="Enviar" />
                }*@

            </div>
        </div>
    </div>
</div>

Macro_Cronograma_Core/Views/Projeto/tables.cshtml
@model IEnumerable<Macro_Cronograma.models.tb_projeto>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Status de Projetos</h3>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                   Projetos Ativos 
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Projeto</th>
                                <th>Data inicio</th>
                                <th>Data Final</th>
                                <th>Progresso</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr class="projeto-@item.id_projeto">
                                <td>@item.des_projeto</td>
                                <td>@item.dt_inicio.ToShortDateString()</td>
                                <td>@item.dt_fim.ToShortDateString()</td>
                                <td><progress value="@DateTime.Now.DayOfYear" max="@item.dt_fim.DayOfYear"></progress></td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<!-- /#page-wrapper -->


<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
</script>

Macro_Cronograma_Core/Views/Shared/_Layout.cshtml
@model IEnumerable<Macro_Cronograma.models.tb_projeto>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Macro Cronograma</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="~/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="~/vendor/morrisjs/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")"> Macro Cronograma</a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 1</strong>
                                        <span class="pull-right text-muted">40% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                            <span class="sr-only">40% Complete (success)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 2</strong>
                                        <span class="pull-right text-muted">20% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                            <span class="sr-only">20% Complete</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 3</strong>
                                        <span class="pull-right text-muted">60% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                            <span class="sr-only">60% Complete (warning)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 4</strong>
                                        <span class="pull-right text-muted">80% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                            <span class="sr-only">80% Complete (danger)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Tasks</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard fa-fw"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Projetos<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                @foreach (var item in Model)
                                {
                                    <li>
                                        <a href="@Url.Action("Projeto", "Projeto", new { id = item.id_projeto})">@item.des_projeto</a>
                                    </li>
                                }
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="@Url.Action("Tables","Projeto")">
                                <i class="fa fa-table fa-fw"></i> Status de projetos
                            </a>
                        </li>

                        <li>
                            <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#">Second Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Second Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->

        </nav>
        </div>
        @RenderBody()

        <script src="~/vendor/jquery/jquery.min.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="~/vendor/metisMenu/metisMenu.min.js"></script>

        <!-- Morris Charts JavaScript -->
        <script src="~/vendor/raphael/raphael.min.js"></script>
        <script src="~/vendor/morrisjs/morris.min.js"></script>
        <script src="~/data/morris-data.js"></script>

        <!-- Custom Theme JavaScript -->
        <script src="~/dist/js/sb-admin-2.js"></script>

</body>

</html>